resources:
  repositories:
    - repository: provisioning
      type: github
      endpoint: "Github"
      name: spyder007/provisioning-projects


trigger: none
pr: none

jobs:
- job: build_base
  displayName: Build Base Image
  timeoutInMinutes: 60
  pool:
    name: Provisioning
  steps:
    - checkout: self
      path: s/automation
    - checkout: provisioning
      path: s/provisioning
    - task: DownloadSecureFile@1
      name: secretvars
      inputs:
        secureFile: ubuntu-base-secrets.pkrvars.hcl
    - pwsh: |     
        $addPath = "C:\Program Files\OpenSSL-Win64\bin"
        $regexAddPath = [regex]::Escape($addPath)
        $arrPath = $env:Path -split ';' | Where-Object {$_ -notMatch "^$regexAddPath\\?"}
        $env:Path = ($arrPath + $addPath) -join ';'
        Write-Host "Import provisioning modules"
        Get-childItem "$(Build.SourcesDirectory)\provisioning\*.psm1" | % { Import-Module $_.FullName -Force }

        Write-Host "Build Base Image"
        Push-Location "$(Build.SourcesDirectory)\provisioning"
        Build-UbuntuBase -SecretVariableFile $(secretvars.secureFilePath) -OutputFolder "$(Build.StagingDirectory)\bases\" -machineName "ubuntu-2204-base"

        New-Item -ItemType Directory "\\cloud.gerega.net\Images\bases\ubuntu-$(Build.BuildNumber)"

      displayName: Build Ubuntu Base Image
    - task: CopyFiles@2
      displayName: Copy Files to Synology
      inputs:
        SourceFolder: $(Build.StagingDirectory)\bases\
        Contents: "**"
        TargetFolder: "\\\\cloud.gerega.net\\Images\\bases\\ubuntu-$(Build.BuildNumber)
        OverWrite: true


      
        