trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - terraform/devops/*
      - .devops/pipeline-tf-azure-geregalab.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/devops/*
      - .devops/pipeline-tf-azure-geregalab.yaml
      

variables:
  - group: 'terraform-azure-geregalab'
  - group: 'terraform-s3-backend'
  - group: 'terraform-hcvault'

extends:
  template: template-terraform.yaml
  parameters:
    terraformDirectory: 'terraform/geregalab'
    addVaultAuthentication: true
    planArguments: '-var-file config/gerega.tfvars'