trigger: none
pr: none
schedules:
  - cron: "0 5 16 * *"
    displayName: "Cleanup Agents"
    always: true
    branches:
      include:
        - main

resources:
  repositories:
    - repository: provisioning
      type: github
      endpoint: "Github"
      name: spyder007/provisioning-projects

variables:
  - group: auth-api-credentials
  - group: ms-agent-settings
  - group: proxmox-settings

# This pipeline is used to disable and cleanup old build agents.  
# Disabling old agents first is required, as you cannot delete an agent that is currently running a job.

jobs:
  - job: disable_build_agents
    displayName: Disable Build Agents
    timeoutInMinutes: 560
    pool:
      name: Default
    steps:
      - checkout: self
        path: s/automation
      - checkout: provisioning
        path: s/provisioning
      - pwsh: |
          Write-Host "Import provisioning modules"
          Get-childItem "$(Build.SourcesDirectory)\provisioning\*.psm1" | % { Import-Module $_.FullName -Force }
          Install-Module -Name Corsinvest.ProxmoxVE.Api -Force

          Write-Host "Set Proxmox Settings"
          Set-ProxmoxSettings -hostsAndPorts $(proxmox-host) -apiToken $(proxmox-api-token)

          Write-Host "Disable Old Build Agents"
          Push-Location "$(Build.SourcesDirectory)\provisioning"
          .\Disable-OldBuildAgents.ps1 -devOpsOrg "$(agent-org)" -devOpsUsername "$(devops-username)" -devOpsPat "$(agent-pat)" -devOpsPool "Default"

        displayName: Disable Old Build Agents
        name: disable_old_build_agents

  - job: cleanup_build_agents
    displayName: Cleanup Build Agents
    dependsOn: disable_build_agents
    timeoutInMinutes: 560
    pool:
      name: Default
    steps:
      - checkout: self
        path: s/automation
      - checkout: provisioning
        path: s/provisioning
      - pwsh: |
          Write-Host "Import provisioning modules"
          Get-childItem "$(Build.SourcesDirectory)\provisioning\*.psm1" | % { Import-Module $_.FullName -Force }
          Install-Module -Name Corsinvest.ProxmoxVE.Api -Force

          Write-Host "Configure Unifi Client Settings"
          Set-AuthApiEnvironmentVariables -authUrl $(auth-url) -clientId $(auth-client-id) -clientSecret "$(auth-client-secret)" -userName $(auth-username) -password "$(auth-password)"
          Set-UnifiEnvironmentVariables -provisionUrl $(unifi-wrapper-url) -provisionGroup $(unifi-provisioning-group)

          Write-Host (Get-AuthApiEnvironmentVariables | ConvertTo-Json)
          Write-Host (Get-UnifiEnvironmentVariables | ConvertTo-Json)

          Write-Host "Set Proxmox Settings"
          Set-ProxmoxSettings -hostsAndPorts $(proxmox-host) -apiToken $(proxmox-api-token)

          Write-Host "Cleanup Old Build Agents"
          Push-Location "$(Build.SourcesDirectory)\provisioning"
          .\Delete-OldBuildAgents.ps1 -devOpsOrg "$(agent-org)" -devOpsUsername "$(devops-username)" -devOpsPat "$(agent-pat)" -devOpsPool "Default"

        displayName: Cleanup Old Build Agents
        name: cleanup_build_agents
