trigger: none
pr: none
schedules:
- cron: "0 0 * * 0"
  displayName: "Renew Tokens"
  always: true
  branches:
    include: 
      - main

resources:
  repositories:
    - repository: argo
      type: github
      endpoint: "Github"
      name: spydersoft-consulting/ops-argo
    - repository: internal
      type: github
      endpoint: "Github"
      name: spydersoft-consulting/ops-internal-cluster
    - repository: nonprod
      type: github
      endpoint: "Github"
      name: spydersoft-consulting/ops-nonprod-cluster
    - repository: prod
      type: github
      endpoint: "Github"
      name: spydersoft-consulting/ops-prod-cluster

jobs:
  - job: update_libraries
    displayName: Renew Tokens
    pool:
      name: Default
    steps:
      - pwsh: |     
          ls $(Build.SourcesDirectory)

