resources:
  repositories:
    - repository: provisioning
      type: github
      endpoint: "Github"
      name: spyder007/provisioning-projects


trigger: none
pr: none

jobs:
- job: Test
  displayName: Test
  pool:
    name: Provisioning
  steps:
    - checkout: self
    - checkout: provisioning
    - pwsh: | 
        ls $(Build.SourcesDirectory)
        