resources:
  repositories:
    - repository: provisioning
      type: github
      endpoint: "Github"
      name: spyder007/provisioning-projects


trigger: none
pr: none

jobs:
- job: Test
  displayName: Test
  pool:
    name: Provisioning
  steps:
    - checkout: self
      path: s/automation
    - checkout: provisioning
      path: s/provisioning
    - pwsh: | 
        Write-Host "Import provisioning modules"
        Get-childItem "$(Build.SourcesDirectory)\provisioning\*.psm1 | % { Import-Module $_.FullName -Force }
        ls $(Build.SourcesDirectory)
        