trigger: none
pr: none

variables:
  - group: 'terraform-azuread'
  - group: 'terraform-s3-backend'

jobs:
- job: renew_tokens
  displayName: Renew Tokens
  pool:
    name: Default
  steps:
    - pwsh: |
        terraform init
      displayName: 'Initialize Terraform'
      workingDirectory: $(System.DefaultWorkingDirectory)/terraform/azuread
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_ENDPOINT_URL_S3: $(AWS_ENDPOINT_URL_S3)