trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - terraform/devops/*
      - .devops/pipeline-tf-azure-devops.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/devops/*
      - .devops/pipeline-tf-azure-devops.yaml

# Secrets may change when terraform-azuread runs.  When the
#  terraform-azuread pipeline runs from main, kick off this build
resources:
  pipelines:
    - pipeline: terraform-azuread
      source: terraform-azuread
      project: Ops
      trigger:
        branches:
          include:
            - main

variables:
  - group: "terraform-azure-devops"
  - group: "terraform-s3-backend"
  - group: "terraform-hcvault"

extends:
  template: template-terraform.yaml
  parameters:
    tofuDirectory: "terraform/devops"
    addVaultAuthentication: true
    planArguments: "-var-file config/gerega.tfvars"
    includeAzureDevopsVariables: true
