trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - terraform/devops/*
      - .devops/pipeline-tf-azure-devops.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/devops/*
      - .devops/pipeline-tf-azure-devops.yaml

variables:
  - group: 'terraform-azure-devops'
  - group: 'terraform-s3-backend'

extends:
  template: template-terraform.yaml
  parameters:
    terraformDirectory: 'terraform/devops'