trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - terraform/azuread/*
      - .devops/pipeline-tf-azuread.yaml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/azuread/*
      - .devops/pipeline-tf-azuread.yaml

variables:
  - group: 'terraform-azuread'
  - group: 'terraform-s3-backend'

extends:
  template: template-terraform.yaml
  parameters:
    terraformDirectory: 'terraform/azuread'
    planArguments: '-var-file config/gerega.tfvars'