minio_address            = "https://gs3.mattgerega.net"
git_email                = "geregam@gmail.com"
git_name                 = "Matt Gerega"
unifi_wrapper_url        = "https://api.mattgerega.com/unifi/ipmanager"
unifi_provisioning_group = "virtual"